### ISSUE TITLE
KeyError: 'media_type' when backing up 

### ISSUE THREAD

**Issue by locoda** [one-among-us/TelegramBackup#3]
Hey 😊 (not sure it's better to communicate in English or Chinese but I guess I'll go with English first)
I was trying to back up my telegram channel @ethersdaily using this tool (and further hosted it somewhere). I tried the GitHub Actions but it failed at `tgc` step (full log [here](https://github.com/locoda/my-telegram-channel-data/actions/runs/3909819649/jobs/6681507138)), and I can also reproduce this error locally on my own mac. 
I'd really appreciate if you can take a look as I haven't further dig into it. Let me know if you need any other information to reproduce this issue 😛

Related log looks like:
```
Login success! ID: 1170807065 | is_bot: True
Chat obtained. Chat name: 乙醚的小烧杯 | Type: ChatType.CHANNEL | ID: -1001161765463
Crawling channel posts...
> 178 total messages... (up to ID #200)
> 375 total messages... (up to ID #400)
[Bot] Waiting for 30 seconds before continuing (required by "channels.GetMessages")
> 568 total messages... (up to ID #600)
> 764 total messages... (up to ID #800)
[Bot] Waiting for 30 seconds before continuing (required by "channels.GetMessages")
> 962 total messages... (up to ID #1000)
> 1155 total messages... (up to ID #1200)
[Bot] Waiting for 30 seconds before continuing (required by "channels.GetMessages")
> 1353 total messages... (up to ID #1400)
> 1551 total messages... (up to ID #1600)
[Bot] Waiting for 29 seconds before continuing (required by "channels.GetMessages")
> 1751 total messages... (up to ID #1800)
> 1853 total messages... (up to ID #2000)
> 1853 total messages... (up to ID #2200)
> All 200 messages are empty, we're done.
Downloading 2.jpg...
Traceback (most recent call last):
  File "/usr/local/bin/tgc", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.10/site-packages/tgc/pyro/crawl.py", line 177, in run
    asyncio.get_event_loop().run_until_complete(run_app())
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.10/site-packages/tgc/pyro/crawl.py", line 159, in run_app
    await process_chat(int(export["chat_id"]), Path(export["path"]))
  File "/usr/local/lib/python3.10/site-packages/tgc/pyro/crawl.py", line 143, in process_chat
    results = [await process_message(m, path) for m in msgs]
  File "/usr/local/lib/python3.10/site-packages/tgc/pyro/crawl.py", line 143, in <listcomp>
    results = [await process_message(m, path) for m in msgs]
  File "/usr/local/lib/python3.10/site-packages/tgc/pyro/crawl.py", line 91, in process_message
    if f['media_type'] == 'photo' or (not f['media_type'] and (m['file'].get('mime_type') or "").startswith("image")):
KeyError: 'media_type'
```

**Comment by hykilpikonna** [comment]
Just replaced subscripting with null-safe `dict.get()`, should be fixed now even though I haven't tested it.

You can run the latest branch by changing the action's install command from `pip install tgc` to:

```shell
pip install git+https://github.com/one-among-us/TelegramBackup.git@main
```

**Comment by hykilpikonna** [comment]
Please let me know if the fix works or if there are further issues!

**Comment by locoda** [comment]
I think this works fine for me now!

**Comment by hykilpikonna** [comment]
Okay, thanks for the confirmation. Just deployed [v1.0.6](https://pypi.org/project/tgc/1.0.6/) with the fix to PyPI.
